### ISSUE TITLE
MdePopover on top MatDialog

### ISSUE THREAD

**Issue by pacocom** [joejordanbrown/popover#60] opened 2019-08-28 07:07 UTC
I have the same problem, any solution?

I am using **MatDialog** https://material.angular.io/components/dialog/api and **MdePopover** https://github.com/joejordanbrown/popover/blob/master/projects/material-extended/mde/src/lib/popover/popover.md

I want MatDialog on top of MdePopover

![image](https://user-images.githubusercontent.com/7735329/63833364-258e1000-c973-11e9-964b-8e9d9f02a052.png)

Very Thank!

**Comment by joejordanbrown** [comment] 2019-08-28 13:28
@pacocom 

Please create a demo using our StackBlitz template here https://stackblitz.com/edit/mde-popover, I will then be able to debug what the issue is and help to resolve it.

**Comment by pacocom** [comment] 2019-08-29 16:44
I added code this https://stackblitz.com/edit/mde-popover

Thank!

**Comment by joejordanbrown** [comment] 2019-08-29 17:56
@pacocom 

This is a timing issue with the popover and MatDialog, maybe settings the `mdePopoverEnterDelay` to `0` would help for certain scenarios. Both of the popover and dialog use the `@angular/cdk` for the overlay.

Can you show a real-life example where this would happen? Since triggering them both via `ngOnInit` at the same time is not realistic, and this wouldn't happen when using trigger hover and a dialog opening programmatically at the same time. 

A solution, if you have to trigger them both at the same time, would be to increase the `z-index` for the dialog, see https://stackblitz.com/edit/mde-popover-oyykw6?file=styles.scss

If you require the backdrop to be above the popover you will also need to increase the `z-index` on that while the dialog is open and decrease when the dialog is closed.

**Comment by joejordanbrown** [comment] 2019-09-04 20:12
@pacocom I'm closing this for now. If you come back with a reply, ping my username so I can get notified.

**Closed by joejordanbrown** 2019-09-04 20:12 UTC
Labels: question

**Comment by pacocom** [comment] 2019-09-05 09:52
Ok!, sorry for the late answer.

A example: if I need to open in a view a popover and inside the view a onboarding.

Very thanks.

**Comment by joejordanbrown** [comment] 2019-09-09 16:11
@pacocom 

If you can showcase that, and the issues are not caused by a programming error on your part. I can look into it and showcase this issue to the @angular/cdk/overlay team because that is what controls the order of overlays in Material and this popover.
